### PR TITLE
A couple updates to Goalie

### PR DESCRIPTION
**Pull request by adamcooper**
Hi Helder,

I like your local? delegation update and thanks for including the previous set of commits by my co-worker.

Here is a summary of the changes:

I've updated the gemspec for the proper dependencies of activesupport and actiondispatch.  Extracted the instance error variables into a module to be included on a controller level.  Allows for easier integration with the public error controller.  Finally, the 'consider_all_requests_local' flag is now passed down into the initializer.

Cheers,
Adam

### CODE REVIEW

**Comment by hsribei** [comment]
Hi Adam, thank you for your changes. The gemfile is autogenerated by Jeweler through the Rakefile, so you can't change that manually. I added the same `add_runtime_dependency` calls to the Rakefile, but when running rake install it complains:

```
ERROR:  Error installing ./pkg/goalie-0.0.3.gem:
    activemodel requires activesupport (= 3.0.1, runtime)
```

I don't know where this activemodel dependency came from, but it's stopping me from pulling in your changes. Do you know how this could be solved (I'm not the biggest expert in dependency management)?

**Comment by adamcooper** [comment]
I'm sending you an updated pull request with a fix that fixes the issue.

It seems that order matters for the gemspec.  I originally had it activesupport then actionpack and I received the same error that you did.  Switching it fixed the issue.  

I don't understand the intricacies of dependency management either.

Cheers,
Adam

**Comment by adamcooper** [comment]
Hmm. It seems that github automatically added a file to the pull request.  Sweet.

**Comment by adamcooper** [comment]
Adding a comment so you get this pull request.  

I'm not 100% with the pull requests but more confident w/ Goalie so I'm removing the warning so that it might not scare off other users.

**Comment by hsribei** [comment]
Pulled. Thanks! :)

**Pull request merged**
